# Generated by Django 4.0.5 on 2023-03-13 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='hashed',
        ),
    ]
