# Generated by Django 4.0.5 on 2023-02-26 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='kategoriaKarta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod_kategoria', models.CharField(max_length=10, verbose_name='Kodigu Kategoria')),
                ('naran_kategoria', models.CharField(max_length=100, verbose_name='Naran Kategoria')),
                ('hashed', models.CharField(max_length=32, null=True)),
            ],
            options={
                'verbose_name_plural': 'Kategoria Karta',
            },
        ),
        migrations.CreateModel(
            name='kartaTama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nu_karta_tama', models.CharField(max_length=20, verbose_name='Numeru Karta Tama')),
                ('subject_karta_tama', models.CharField(max_length=100, verbose_name='Subject Karta Tama')),
                ('deskrisaun_karta_tama', models.TextField(verbose_name='Deskrisaun Karta Tama')),
                ('data_karta_tama', models.DateTimeField(auto_now_add=True)),
                ('orijen_karta_tama', models.CharField(max_length=100, verbose_name='Orijen Karta Tama')),
                ('entrega_husi', models.CharField(max_length=100, verbose_name='Karta Entrega Husi')),
                ('klasifikasaun', models.CharField(choices=[('Urgente', 'Urgente'), ('Normal', 'Normal'), ('Konfidensial', 'Konfidensial')], max_length=32, null=True)),
                ('naran_folder', models.CharField(max_length=50, null=True, verbose_name='Naran Folder')),
                ('naran_file', models.FileField(max_length=200, null=True, upload_to='', verbose_name='Naran File')),
                ('hashed', models.CharField(max_length=32, null=True)),
                ('kategoria_karta_tama', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='KartaTama.kategoriakarta')),
                ('tinan_karta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom.tinan')),
            ],
            options={
                'verbose_name_plural': 'Karta Tama',
            },
        ),
    ]
