# Generated by Django 4.0.5 on 2023-03-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KartaTama', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kartatama',
            name='nu_karta_tama',
            field=models.CharField(max_length=20, unique=True, verbose_name='Numeru Karta Tama'),
        ),
    ]
