# Generated by Django 4.0.5 on 2023-03-07 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_alter_tinan_options_alter_tinan_tinan'),
        ('KartaTama', '0002_alter_kartatama_nu_karta_tama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kartatama',
            name='tinan_karta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Karta_Tama', to='custom.tinan'),
        ),
    ]
