# Generated by Django 4.0.5 on 2023-03-07 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KartaTama', '0003_alter_kartatama_tinan_karta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kartatama',
            name='kategoria_karta_tama',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Kategoria_Karta_Tama', to='KartaTama.kategoriakarta'),
        ),
    ]
