# Generated by Django 4.0.5 on 2023-02-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tinan',
            options={'verbose_name_plural': 'Tinan'},
        ),
        migrations.AlterField(
            model_name='tinan',
            name='tinan',
            field=models.CharField(max_length=10, verbose_name='Tinan'),
        ),
    ]
