# Generated by Django 4.0.5 on 2023-03-07 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KartaTama', '0004_alter_kartatama_kategoria_karta_tama'),
        ('custom', '0002_alter_tinan_options_alter_tinan_tinan'),
        ('KartaSai', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='kartaTama',
            new_name='kartaSai',
        ),
    ]
