# Generated by Django 4.0.5 on 2023-03-13 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KartaSai', '0002_rename_kartatama_kartasai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kartasai',
            name='entrega_husi',
            field=models.CharField(max_length=100, verbose_name='Karta Hatoo Ba'),
        ),
    ]
